UrbanCCD-UChicago/plenario2

config/test.exs
config/travis.exs
lib/plenario2/core/actions/user_actions.ex
lib/plenario2/core/changesets/user_changesets.ex
test/plenario2/core/user_action_test.exs

testing with `--filter user` shows all green

tested users

---

lib/plenario2/core/actions/user_actions.ex
test/plenario2/core/meta_actions_test.exs
test/plenario2/core/meta_schema_test.exs
test/plenario2/core/user_action_test.exs

- removed `_user` from action names
- updated calls elsewhere

removed redundant user from action names

---

lib/plenario2/core/actions/data_set_field_actions.ex
lib/plenario2/core/actions/virtual_date_field_actions.ex
lib/plenario2/core/actions/virtual_point_file_actions.ex
lib/plenario2/core/changesets/data_set_field_changesets.ex
lib/plenario2/core/changesets/virtual_date_field_changesets.ex
lib/plenario2/core/changesets/virtual_point_field_changesets.ex
test/plenario2/core/data_set_field_test.exs
test/plenario2/core/virtual_date_field_actions_test.exs
test/plenario2/core/virtual_point_field_actions_test.exs

- tested data set fields
- tested virtual date fields
- tested virtual point fields
I kinda want to roll in the constraints, but I think that would make this PR a little too heavy. Watch for that to follow soon. It's gonna be a whopper.

Test fields

---

lib/plenario2/core/actions/data_set_constraint_actions.ex
lib/plenario2/core/changesets/data_set_constraint_changesets.ex
lib/plenario2/core/changesets/virtual_date_field_changesets.ex
lib/plenario2/core/changesets/virtual_point_field_changesets.ex
test/plenario2/core/data_set_constraint_actions_test.exs
test/plenario2/core/virtual_date_field_actions_test.exs
test/plenario2/core/virtual_point_field_actions_test.exs

- actions and test for `DataSetFieldConstraints`
- validating constraint and virtual fields' fields exist (the yo dawg principle)

Test constaints

---

lib/plenario2/core/actions/data_set_diff_actions.ex
lib/plenario2/core/actions/etl_job_actions.ex
lib/plenario2/core/changesets/data_set_diff_changesets.ex
lib/plenario2/core/changesets/etl_job_changesets.ex
lib/plenario2/core/schemas/data_set_diff.ex
lib/plenario2/core/schemas/etl_job.ex
priv/repo/migrations/20171110180027_create_data_set_diffs.exs
priv/repo/migrations/20171117153045_add_etl_job_error.exs
test/plenario2/core/data_set_diff_actions_test.exs
test/plenario2/core/etl_job_actions_test.exs

- etl jobs
- data set diffs
these two go hand in hand, like the fields and constraints, so here you go

Test etl jobs

---

.travis.yml
lib/plenario2/core/actions/data_set_actions.ex
priv/repo/migrations/20171110000000_postgis_extension.exs
test/plenario2/core/data_set_actions_test.exs

- private functions to generate sql for:
- creating a dataset table
- creating parsing functions for timestamps and points
- creating trigger functions for parsers
- adding triggers
- adding constraints to dataset tables
- public functions for
- creating a table with its constraints, parsing functions and
triggers
- dropping a table
plus tests; glorious, glorious tests!

Data Set Actions

---

README.md

their service doesn't work and i don't want a badge on the readme that
makes it look like our project is broken when it isn't.

removed hexfaktor badge

---

config/config.exs
lib/plenario2_auth/abilities.ex
lib/plenario2_auth/error_handler.ex
lib/plenario2_auth/pipeline.ex
lib/plenario2_web.ex
lib/plenario2_web/controllers/meta_controller.ex
lib/plenario2_web/router.ex
mix.exs
mix.lock
test/plenario2_web/controllers/meta_controller_test.exs

- cleaned up pipeline names
- refactored auth helpers
- added canary/canada to abstract user authorization
fixes #49

Cleaned Up Auth System

---

lib/plenario2/actions/data_set_actions.ex
lib/plenario2/actions/etl_job_actions.ex
lib/plenario2/changesets/data_set_constraint_changesets.ex
lib/plenario2/changesets/export_job_changesets.ex
lib/plenario2/changesets/virtual_date_field_changesets.ex
lib/plenario2/changesets/virtual_point_field_changesets.ex
lib/plenario2/schemas/meta.ex
lib/plenario2_auth/user_actions.ex
lib/plenario2_web/controllers/admin_controller.ex
lib/plenario2_web/router.ex
lib/plenario2_web/templates/meta/detail.html.eex
test/plenario2/data_set_actions_test.exs
test/plenario2/data_set_constraint_actions_test.exs
test/plenario2/data_set_diff_actions_test.exs
test/plenario2/etl_job_actions_test.exs
test/plenario2/meta_actions_test.exs
test/plenario2/meta_schema_test.exs
test/plenario2_auth/user_action_test.exs
test/plenario2_etl/scheduled_jobs_test.exs
test/plenario2_web/controllers/admin_controller_test.exs
test/plenario2_web/controllers/meta_controller_test.exs

- swapped `dataset` for `data_set` in function and variable names
- swapped `dataset` for `data-set` in URLs
- swapped `pk` for `id` in function and variable names

Names Clean Up

---

lib/plenario2_web/controllers/meta_controller.ex
mix.exs

added a logging statement and bumped version to test out deployment pipeline

added logging statement

---

lib/plenario2_web/templates/meta/detail.html.eex

explicitly set method to GET on buttons

---

lib/plenario2/actions/admin_user_note_actions.ex
lib/plenario2/actions/data_set_constraint_actions.ex
lib/plenario2/actions/data_set_diff_actions.ex
lib/plenario2/actions/data_set_field_actions.ex
lib/plenario2/actions/etl_job_actions.ex
lib/plenario2/actions/export_job_actions.ex
lib/plenario2/actions/virtual_date_field_actions.ex
lib/plenario2/actions/virtual_point_field_actions.ex
lib/plenario2/changesets/meta_changesets.ex
lib/plenario2/guards.ex

Struct/ID Agnostic Actions and Fix Nasty Date Comp Bug

---

lib/plenario2/actions/admin_user_note_actions.ex
lib/plenario2/actions/etl_job_actions.ex
lib/plenario2/actions/meta_actions.ex
lib/plenario2/changesets/data_set_constraint_changesets.ex
lib/plenario2/changesets/export_job_changesets.ex
lib/plenario2/changesets/virtual_date_field_changesets.ex
lib/plenario2/changesets/virtual_point_field_changesets.ex
lib/plenario2/queries/admin_user_note_queries.ex
lib/plenario2_etl/worker.ex
lib/plenario2_web/controllers/admin_controller.ex
lib/plenario2_web/controllers/admin_user_note_controller.ex
lib/plenario2_web/controllers/data_set_constraint_controller.ex
lib/plenario2_web/controllers/data_set_field_controller.ex
lib/plenario2_web/controllers/meta_controller.ex
lib/plenario2_web/controllers/virtual_date_field_controller.ex
lib/plenario2_web/controllers/virtual_point_field_controller.ex
test/plenario2/etl_job_actions_test.exs
test/plenario2/meta_actions_test.exs
test/plenario2_web/controllers/admin_controller_test.exs
test/plenario2_web/controllers/admin_user_note_controller_test.exs
test/plenario2_web/controllers/meta_controller_test.exs

Internal API Consistency

---

lib/plenario2/actions/data_set_actions.ex
lib/plenario2/actions/meta_actions.ex
lib/plenario2/actions/templates/add_constraint.sql.eex
lib/plenario2/actions/templates/create_parse_location_function.sql.eex
lib/plenario2/actions/templates/create_parse_long_lat_function.sql.eex
lib/plenario2/actions/templates/create_parse_timestamp_function.sql.eex
lib/plenario2/actions/templates/create_point_trigger_function.sql.eex
lib/plenario2/actions/templates/create_table.sql.eex
lib/plenario2/actions/templates/create_timestamp_trigger_function.sql.eex
lib/plenario2/actions/templates/create_trigger.sql.eex
lib/plenario2/actions/templates/drop_table.sql.eex
test/plenario2/data_set_actions_test.exs
test/plenario2/meta_actions_test.exs
test/plenario2_etl/worker_test.exs

- switched SQL to template files
- explicitly checking SQL results
- added logging for success and error
- when a meta is approved the process of creating the data set table and its various db functions and triggers and constraints will be run
closes #101

Better DataSetActions Functions

---

lib/plenario2/actions/data_set_actions.ex
lib/plenario2/actions/data_set_constraint_actions.ex
lib/plenario2/actions/templates/add_constraint.sql.eex
lib/plenario2/changesets/data_set_constraint_changesets.ex
lib/plenario2_web/controllers/data_set_constraint_controller.ex
lib/plenario2_web/controllers/meta_controller.ex
lib/plenario2_web/router.ex
lib/plenario2_web/templates/data_set_constraint/create.html.eex
lib/plenario2_web/templates/data_set_constraint/edit.html.eex
lib/plenario2_web/templates/meta/detail.html.eex
test/plenario2/data_set_constraint_actions_test.exs

- fixed a bug in the add constraint data set actions
- added update functions to changesets, actions and controller
- updated templates
- updated tests
closes #116

Ds constraint update changeset

---

lib/plenario2/actions/virtual_date_field_actions.ex
lib/plenario2/changesets/virtual_date_field_changesets.ex
lib/plenario2_web/controllers/virtual_date_field_controller.ex
lib/plenario2_web/router.ex
lib/plenario2_web/templates/meta/detail.html.eex
lib/plenario2_web/templates/virtual_date_field/edit.html.eex
test/plenario2/virtual_date_field_actions_test.exs

- added functions to changeset
- added function to actions
- updated tests
- updated controller
- added template
- updated meta detail template
- added routes
closes #117

Update virtual date

---

lib/plenario2_web/controllers/admin_controller.ex

logging within admin interface

admin logging statements

---

lib/plenario2_web/controllers/data_set_field_controller.ex

Fixed Bug in DataSetFieldController.update

---

config/config.exs
config/test.exs
lib/plenario2/actions/admin_user_note_actions.ex
lib/plenario2/actions/meta_actions.ex
lib/plenario2_mailer.ex
lib/plenario2_mailer/emails.ex
mix.exs
mix.lock
test/plenario2_mailer/test_email.exs

Added Email Capability

---

Dockerfile
build
deploy

Updated Build and Deploy Scripts

---

lib/model_registry.ex
lib/postgres_extensions.ex

So let's be honest here, when my biggest data provider formats their
date time strings as `mm/dd/YYYY HH:MM:SS A` I'm going to have a rough
time parsing that into a database with a language that is vehemently
opposed to non-ISO and UTC date times.
So, being the nice guy that I am, I decide I'm going to make a custom
type for importint their wacky data: `ForgivingDatetime`.
Basically all this bad boy does is check for an ISO 8601 or US Standard
date string and parse it down into integer tuples that Elixir will place
nicely with.
Closes #170

The Forgiving Type

---

lib/plenario/actions/meta_actions.ex
lib/plenario/actions/sql-templates/create-parse-location-func.sql.eex
lib/plenario/actions/sql-templates/create-parse-points-trigger.sql.eex
test/plenario/data_set_actions_test.exs
test/plenario/meta_actions_test.exs

I didn't include tests for parsing _location_ -- just lat/lon pairs.
Derp.
Closes #174

Fixed Location Parsing Bug

---

lib/plenario_web/controllers/web/page_controller.ex
mix.exs
test/plenario_web/controllers/web/page_controller_test.exs

Fix mixed srids 179

---

lib/plenario.ex
lib/plenario/actions/meta_actions.ex
lib/plenario_web/templates/shared/line.html.eex
lib/plenario_web/templates/web/page/explorer.html.eex
lib/plenario_web/views/shared_view.ex
mix.exs
test/plenario_web/controllers/web/page_controller_test.exs

Pretty search results

---

lib/model_registry.ex
lib/plenario_web/controllers/web/export_controller.ex
lib/plenario_web/router.ex
lib/plenario_web/templates/web/page/explorer.html.eex
lib/plenario_web/views/web/export_view.ex

Added ability to start export jobs for logged in users from the search
results.
Closes #185

Wired up Exports in Search Results

---

config/travis.exs
lib/plenario_web.ex
lib/plenario_web/controllers/web/admin_user_note_controller.ex
lib/plenario_web/controllers/web/data_set_controller.ex
lib/plenario_web/controllers/web/data_set_field_controller.ex
lib/plenario_web/controllers/web/unique_constraint_controller.ex
lib/plenario_web/controllers/web/virtual_date_controller.ex
lib/plenario_web/controllers/web/virtual_point_controller.ex
lib/plenario_web/error_view.ex
lib/plenario_web/templates/web/404_page.html.eex

- custom 404 page
- web controllers now get objects or 404
Closes #191

Better 404

---

config/travis.exs
lib/plenario_web/error_view.ex
lib/plenario_web/templates/500_page.html.eex

Added something a little nicer than the plaintext `Internal Error`.
Closes #192

Custom 500 Page

---

lib/plenario_etl/exporter.ex
lib/plenario_mailer/emails.ex
test/plenario_etl/exporter_test.exs

- Send email with simple message reporting success or failure
- Success emails contain a link to the file hosted on s3

Export emails

---

config/config.exs
lib/plenario_etl/exporter.ex

- Sets `@bucket` for `PlenarioEtl.Exporter`

Set bucket setting to "plenario-exports-#{env}"

---

assets/package-lock.json
assets/package.json

- CVE for moment.js
- removed leaflet heatmap since it's broken

Updated JS Libs

---

lib/plenario_etl/actions/export_job_actions.ex
lib/plenario_etl/exporter.ex
lib/plenario_mailer/emails.ex
mix.exs
test/plenario_etl/exporter_test.exs
test/support/etl_case.ex

I was not calling `deliver_now` with exporter emails :man_facepalming: 
- Bump to version `0.2.5`
- Add assertions for sent emails

Assert emails are sent

---

lib/plenario/queries/meta_queries.ex
lib/plenario_web/router.ex
test/plenario_web/controllers/web/me_controller_test.exs

- Add a new scope that pipes through `[:browser, :ensure_authenticated]`
- Put all of `/me` resources under that scope
Fixes #225

Create scope piped through :ensure_authenticated

---

lib/field_guesser.ex

We were getting silent errors, and I couldn't figure out for the life of
me where they were coming from.
I backed out the latest change to the module and fixed weaknesses
exposed in the tests that were added. The tests pass and local testing
of the app shows fields being added for files that are processed.
Fixes #222

Fixed Field Guesser

---

lib/plenario/actions/unique_constraint_actions.ex
lib/plenario_etl/worker.ex
priv/data-set-action-sql-templates/create-table.sql.eex
test/plenario_etl/worker_test.exs

Added back Jesse's original code with some API updates. I also found
some errors in the template for bringing up tables - if there are no
fields or constraints it borks, which obviously is a problem for
shapefile base data sets.
Fixes #221

Added Back Shapefile ETL

---

lib/plenario/actions/meta_actions.ex

Per Charlie's request, I changed the dummy observation names so it looks
less beta.

Changed Foo Bar Baz to Less Dumb Dummy Names

---

.iex.exs
lib/plenario_etl/worker.ex
mix.exs

- bumped timeout to 5 minutes (it was only 20 seconds)
- added an `.iex.exs` to make my life easier
Fixes #241

Expand ingest timeout

---

lib/plenario_web/templates/web/page/index.html.eex

Wire up "Add New Data Set"

---

lib/plenario_web.ex
lib/plenario_web/template_helpers.ex
lib/plenario_web/templates/web/data_set/edit.html.eex
lib/plenario_web/templates/web/data_set/show.html.eex
lib/plenario_web/templates/web/data_set_field/edit.html.eex
lib/plenario_web/templates/web/unique_constraint/create.html.eex
lib/plenario_web/templates/web/unique_constraint/edit.html.eex
lib/plenario_web/templates/web/virtual_date/create.html.eex
lib/plenario_web/templates/web/virtual_date/edit.html.eex
lib/plenario_web/templates/web/virtual_point/create.html.eex
lib/plenario_web/templates/web/virtual_point/edit.html.eex
mix.exs

- Close #259 
- Close #258 
- Close #260 #261 #262 (all the blurbs also appear on the edit pages)

Info blocks

---

lib/plenario/changesets/data_set_field_changesets.ex
lib/plenario/schemas/data_set_field.ex
lib/plenario_web/controllers/web/data_set_field_controller.ex
lib/plenario_web/templates/web/data_set/show.html.eex
lib/plenario_web/templates/web/data_set_field/edit.html.eex
mix.exs
priv/repo/migrations/000012_add_description_to_data_set_fields.exs
test/plenario_web/controllers/web/data_set_field_controller_test.exs

- Close #263 
- Might want to create an issue for detail page styling because I jankily crammed description in there

Add description to data set field

---

Dockerfile
README.md
build
deploy

Using tags and other smarter, slimmer deployment methodologies.

Build with Tags

---

config/config.exs
mix.exs
test/plenario_web/controllers/api/detail_controller_test.exs
test/plenario_web/controllers/api/list_controller_test.exs

Options response

---

.tool-versions
README.md

This mostly addresses problems I had myself when setting up my dev environment, but I figured if I had trouble it would be worth clarifying it for others. I took the liberty of making the readme a little prettier and refining some language while I was at it.

Improve documentation for contributors

---

lib/plenario_web/controllers/api/aot_controller.ex
lib/plenario_web/controllers/api/detail_controller.ex
lib/plenario_web/controllers/api/list_controller.ex
lib/plenario_web/controllers/api/plugs.ex
mix.exs
test/plenario_web/controllers/api/aot_controller_test.exs
test/plenario_web/controllers/api/detail_controller_test.exs
test/plenario_web/controllers/api/list_controller_test.exs

Just adds some error messages for the `page` param.
- 422 if page is not a number
- 422 if page is 0 or negative

Page param errors

---

config/config.exs
lib/plenario/actions/meta_actions.ex
lib/plenario_web/template_helpers.ex
lib/plenario_web/templates/web/data_set/show.html.eex
lib/plenario_web/templates/web/page/explorer.html.eex
mix.exs
test/plenario/actions/meta_actions_test.exs
test/plenario_web/controllers/web/page_controller_test.exs

- redid `MetaActions.get_agg_data` to always produce some usable data
- added tests for meta action
I'm running into a bunch of problems with testing still, and they seem
to center around sentry trying to pull a field from the connection
information. I've tried disabling sentry in all envs except prod, but
that doesn't help. My last resort (after spending literally 4 hours
trying to fix it) was to just comment out the test. I've confirmed that
this works in the browser under a bunch of circumstances, but apparently
the connection information in tests screws up sentry...
Fixes #330

330 display graphs

---

lib/plenario_web/controllers/api/plugs.ex
lib/plenario_web/controllers/api/shim_controller.ex
lib/plenario_web/views/api/shim_view.ex
mix.exs
test/plenario_web/controllers/api/shim_controller_test.exs

Shim limit offset keywords

---

lib/plenario_web/controllers/api/detail_controller.ex
lib/plenario_web/controllers/api/list_controller.ex
lib/plenario_web/controllers/api/utils.ex
mix.exs
test/plenario_web/controllers/api/detail_controller_test.exs

398 api pagination

---

lib/postgres_extensions.ex
mix.exs

I added one last catchall pattern that will let everything fall through
to nil. While I don't prefer this method, there still seems to be too
many issues with CoC data sets that aren't producing parseable
timestamps and/or complete data sets.
Also, the auto-formatter went hog wild on the file.
Fixes #400

Fix to erl

---

lib/plenario_web/template_helpers.ex
mix.exs

Fixes error in explorer when dataset is missing upper time bound

Fix explorer strftime error

---

priv/repo/seeds.exs

The created user wasn't an admin -- that's fixed. Also, the
autoformatter went nuts on the file.

Fixed the User Admin Problem

---

test/plenario_web/controllers/api/aot_controller_test.exs

The tests weren't very comprehensive, but they are now. Surprisingly
they didn't uncover any bugs in the controller -- that makes me a little
concerned. Either the controller was written very well or these tests
still aren't covering something. I guess we'll find out.
Fixes #432

Better AoT Controller Tests

---

lib/plenario_auth/abilities.ex
lib/plenario_web/controllers/web/data_set_controller.ex
test/plenario_web/controllers/web/page_controller_test.exs

The abilities module has been updated to match the auth matrix.
I've added a new function to the data set controller to handle missing
slugs and commented out tests that are totally bonkers now that we are
using vue.

Updated Auth

---

assets/src/js/main.js

- Fix issue in the deployed version where `$` cannot be found
- Working in my local production environment

Explicitly import the `$`

---

assets/src/css/_home.scss
assets/src/js/main.js
assets/webpack/webpack.common.js
assets/webpack/webpack.prod.js
config/prod.exs
lib/plenario_web/controllers/web/page_controller.ex
lib/plenario_web/templates/web/layout/app.html.eex
lib/plenario_web/templates/web/page/index.html.eex
mix.exs

This PR fixes 2 issues when frontend is deployed to production
- `$` was not defined
- Images couldn't be found

Fix deployment

---

lib/plenario_aot/aot_worker.ex
mix.exs

Jesus Christ what a freaking mess this has been. We've been getting
inundated with JSON parsing errors at various parts of the process. What
should be a really simple, tightly controlled exchange of information is
a disjointed mess.
This breaks up the code and handles all sorts of situations where we
would otherwise expect a really basic download, parse and insert from a
trusted source.

Handle AoT JSON Parsing Errors

---

assets/src/js/components/DataSetRow.vue
assets/src/js/components/ExplorerSearchResults.vue

`DataSetRow` component was severely lacking in documentation.

Vue Documentation
