UrbanCCD-UChicago/plenario2

lib/plenario2/actions/meta_actions.ex
lib/plenario2/queries/meta_queries.ex
lib/plenario2_web/controllers/meta_controller.ex
lib/plenario2_web/router.ex
lib/plenario2_web/templates/meta/list.html.eex
test/plenario2_web/controllers/meta_controller_test.exs

- changed `/metas` to `/datasets` in the router
- beefed up controller and template
- added new `queries` context to core lib
the new `queries` is intended to work as a means to standardize queries
and make them composable. rather than having
```
Repo.all(from m in Meta, where: m.state == "active", preload: [user:
:metas])
```
all over the place, i think it's nicer to see
```
MetaQueries.list()
|> MetaQueries.with_user()
|> MetaQueries.active_state()
|> Repo.all()
```

Web list metas

---

.gitignore
lib/plenario2/actions/admin_user_note_actions.ex
lib/plenario2/queries/admin_user_note_queries.ex
lib/plenario2/queries/meta_queries.ex
lib/plenario2_auth/guardian.ex
lib/plenario2_auth/user_actions.ex
lib/plenario2_auth/user_changesets.ex
lib/plenario2_web/controllers/meta_controller.ex
lib/plenario2_web/controllers/user_controller.ex
lib/plenario2_web/router.ex
lib/plenario2_web/template_helpers.ex
lib/plenario2_web/templates/layout/app.html.eex
lib/plenario2_web/templates/user/index.html.eex
lib/plenario2_web/templates/user/update_email.html.eex
lib/plenario2_web/templates/user/update_name.html.eex
lib/plenario2_web/templates/user/update_org_info.html.eex
lib/plenario2_web/templates/user/update_password.html.eex
lib/plenario2_web/views/user_view.ex
test/plenario2_web/controllers/meta_controller_test.exs
test/plenario2_web/controllers/user_controller_test.exs
test/plenario2_web/template_helpers_test.exs

users can change:
- name
- email address
- password
- org info
i also fixed a stupid mistake i made in guardian pinning user resources to the email address rather than their id.
closes #22

Self management

---

lib/plenario2/changesets/data_set_field_changesets.ex
lib/plenario2/queries/meta_queries.ex
lib/plenario2_web/controllers/data_set_field_controller.ex
lib/plenario2_web/router.ex
lib/plenario2_web/templates/data_set_field/index.html.eex
lib/plenario2_web/templates/data_set_field/new.html.eex
lib/plenario2_web/views/data_set_field_view.ex
test/plenario2_web/controllers/data_set_field_controller_test.exs

- Adds a `DataSetField` controller with actions for adding and associating new fields to `Meta` instances
- Adds a form for creating these fields
- Adds a simple index page at `/data-sets/:slug/fields`

Workflow for adding new fields to datasets

---

lib/plenario2/changesets/data_set_constraint_changesets.ex
lib/plenario2/changesets/virtual_date_field_changesets.ex
lib/plenario2/changesets/virtual_point_field_changesets.ex
lib/plenario2/queries/meta_queries.ex
lib/plenario2_web/controllers/data_set_constraint_controller.ex
lib/plenario2_web/controllers/meta_controller.ex
lib/plenario2_web/controllers/virtual_date_field_controller.ex
lib/plenario2_web/controllers/virtual_point_field_controller.ex
lib/plenario2_web/router.ex
lib/plenario2_web/templates/data_set_constraint/create.html.eex
lib/plenario2_web/templates/data_set_field/edit.html.eex
lib/plenario2_web/templates/data_set_field/new.html.eex
lib/plenario2_web/templates/meta/detail.html.eex
lib/plenario2_web/templates/virtual_date_field/create.html.eex
lib/plenario2_web/templates/virtual_point_field/create_loc.html.eex
lib/plenario2_web/templates/virtual_point_field/create_long_lat.html.eex
lib/plenario2_web/views/data_set_constraint_view.ex
lib/plenario2_web/views/virtual_date_field_view.ex
lib/plenario2_web/views/virtual_point_field_view.ex
test/plenario2_web/controllers/data_set_constraint_controller_test.exs
test/plenario2_web/controllers/virtual_date_field_controller_test.exs
test/plenario2_web/controllers/virtual_point_field_controller_test.exs

This is a biggun -- it closes out the creation workflows for adding virtual date and point fields and constraints to metas. 
TBH, this is like 80% copy/pasta as they all have more or less the same functionality.
closes #40
closes #41
closes #42

Add fields

---

config/prod.exs
config/test.exs

closes: [#62](https://github.com/UrbanCCD-UChicago/plenario2/issues/62)
left request id logging out of dev since its typically unused clutter

log request ids

---

lib/plenario2/changesets/meta_changesets.ex
lib/plenario2/schemas/meta.ex
lib/plenario2_web/controllers/meta_controller.ex
lib/plenario2_web/templates/meta/update_refresh_info.html.eex

we kinda had these floating around and it made sense to standardize them
on the schema and expose them as _get_ functions.
fixes #95

Made Meta Refresh Rates Standardized

---

lib/plenario2/actions/data_set_field_actions.ex
lib/plenario2/changesets/data_set_field_changesets.ex
test/plenario2/data_set_field_test.exs
test/plenario2_etl/worker_test.exs

this is superfluous when we have unique constraints. PK is a nice
shortcut, but there isn't much benefit to this system having both
options: rather it might make it confusing for non-developer users.
fixes #98

Removed DataSetField `make_primary_key` Functionality

---

lib/plenario2/changesets/data_set_field_changesets.ex
lib/plenario2_web/controllers/data_set_field_controller.ex
lib/plenario2_web/controllers/meta_controller.ex
lib/plenario2_web/templates/data_set_field/edit.html.eex
lib/plenario2_web/templates/meta/detail.html.eex
test/plenario2/data_set_field_test.exs

- added function to DataSetFieldChangesets to disallow updates when meta is ready
- disabled editing in DataSetFieldController when meta is ready
- disabled editing fields in MetaController when meta is ready
- disabled all _Add ..._ buttons in MetaController when meta is ready
i also opened issues to add updates/restrict updates for the other related fields.
closes #112 
closes #119

Disallow field changes when meta ready

---

lib/plenario2/actions/templates/add_constraint.sql.eex
lib/plenario2/actions/templates/create_point_trigger_function.sql.eex
lib/plenario2/actions/templates/create_table.sql.eex
lib/plenario2/actions/templates/create_timestamp_trigger_function.sql.eex
lib/plenario2/actions/templates/create_trigger.sql.eex
lib/plenario2/actions/templates/drop_table.sql.eex
mix.exs
test/plenario2/data_set_actions_test.exs

If a Meta's name contained an illegal character, then the data set
actions would fail. For example, if a data set was named "Chicago Beach
Lab - DNA Tests" the `-` in the name would bomb the entire thing.
After reading and experimenting a lot, the easiest and most reliable
solution is to just quote every name -- table names, function names,
trigger names -- that could contain unlexible values. When surrounded by
quotes, everything is clean. This works for hyphens and non-latin
characters.
fixes #135

Fixed Data Set Table Name Bug

---

README.md
deploy
lib/release_tasks.ex
mix.exs
rel/commands/migrate.sh
rel/config.exs

This adds an executable script that allows us to run migrations from a
release archive rather than uploading the entirety of the source and
having to execute it via `mix`.
You can now run the migrations before starting the application with a
simple flag added to the deploy command:
```
./deploy {{ release_number }} {{ hostname }} --run-migrations
```
:boom:

Release Migrate CMD

---

assets/css/app.css
config/config.exs
config/test.exs
lib/plenario_mailer/admin_user_note.ex
lib/plenario_mailer/admin_user_note_actions.ex
lib/plenario_mailer/admin_user_note_changesets.ex
lib/plenario_mailer/admin_user_note_queries.ex
lib/plenario_web/controllers/admin/meta_controller.ex
lib/plenario_web/controllers/web/admin_user_note_controller.ex
lib/plenario_web/controllers/web/me_controller.ex
lib/plenario_web/router.ex
lib/plenario_web/templates/web/me/index.html.eex
lib/plenario_web/views/web/admin_user_note_view.ex
test/plenario_mailer/admin_user_note_actions_test.exs
test/plenario_mailer/emails_test.exs
test/plenario_web/controllers/admin/meta_controller_test.exs
test/plenario_web/controllers/web/admin_user_note_controller_test.exs

This was kind of left in the dust during the `plenarex` merge.
Closes #167

Redo admin user notes

---

lib/model_registry.ex
lib/plenario/schemas/data_set_field.ex
lib/postgres_extensions.ex
test/fixtures/embedded.json
test/plenario_etl/worker_test.exs

- added a custom type to handle non-strict json
- added tests
- removed geometry type from dsf
We need this because `:map` is too strict. It doesn't allow arrays as
the top level data structure. Something like `{}` is fine, but `[{}]`
blows up.
Closes #173

Load JSON Field Type

---

lib/plenario/actions/meta_actions.ex
lib/plenario/schemas/meta.ex
lib/plenario_etl/etl_job_actions.ex
lib/plenario_web/templates/web/data_set/show.html.eex

All this does is calls the respective MetaActions functions to compute
and set attributes on the Meta.
I also added a function to get a template friendly string for the time
range.
Closes #175

Set Meta Attrs when ETL Job Completes

---

lib/plenario_web/controllers/web/page_controller.ex
lib/plenario_web/router.ex
lib/plenario_web/templates/shared/map.html.eex
lib/plenario_web/templates/web/page/explorer.html.eex
lib/plenario_web/views/shared_view.ex
mix.exs
test/plenario_web/controllers/web/page_controller_test.exs

Let's start with maps:
- now persist bbox and zoom in a more intelligent way
- _much_ cleaner js
Improved search:
- set the form's inputs to correct values
- if the user doesn't set a bbox, the whole map is used
and the zoom backs out to get a cleaner result map
- made search a `GET` request now, so people can share links
I also had to update a test and I bumped the version so we can deploy
this out.
Closes #186

Better Maps and Search UX

---

lib/plenario_web/controllers/web/data_set_controller.ex
lib/plenario_web/templates/web/data_set/show.html.eex

When a meta is no longer _new_, we disable the buttons to edit it and do
any sort of CRUD work on its subordinate models.
The changesets already disallow these changes; this is more cosmetic
than anything.
Closes #166

Disable Edit Functions for Meta and Derivatives

---

lib/plenario/actions/meta_actions.ex
lib/plenario_web/controllers/admin/etl_job_controller.ex
lib/plenario_web/controllers/admin/export_job_controller.ex
lib/plenario_web/router.ex
lib/plenario_web/templates/admin/etl_job/index.html.eex
lib/plenario_web/templates/admin/export_job/index.html.eex
lib/plenario_web/templates/admin/layout/app.html.eex
lib/plenario_web/views/admin/etl_job_view.ex
lib/plenario_web/views/admin/export_job_view.ex

This just creates some simple index dashboards for the admin's ETL/Export tabs.
I'd still like to add some fancy graphs and there are a few features that need to be added to `ExportJob`.
Updates #46

Better admin

---

lib/plenario_etl/worker.ex

```     
|> Enum.map(fn chunk ->
async_load_chunk!(meta, job, chunk, constraints)
end)
|> Enum.map(fn task ->
Task.await(task)
end)
```
This bit of code would spin up thousands of processes for datasets of significant sizes, most of which would time out because they either fail to checkout a poolboy connection or fail to checkout a database connection. They all die en masse and much stress ensues.
Closes #204

Make `load_data` a synchronous process

---

config/config.exs
lib/plenario_etl/scheduled_jobs.ex
lib/plenario_etl/worker.ex
mix.exs
test/plenario_etl/scheduled_jobs_test.exs

**config.exs ->** the interval used put the search date a minute
into the future instead of the past
**scheduled_jobs.ex ->** the ecto query was getting really funky, so i
opted for getting all the ready metas, then filtering out the expired
refreshes, then finding unimported metas and those whose time was in the
range.
**scheduled_jobs_test.exs ->** had to update it to reflect the workflow

Fixed Errors in Scheduler

---

lib/encodings.ex
lib/plenario_etl/actions/etl_job_actions.ex
lib/plenario_etl/actions/export_job_actions.ex
lib/plenario_etl/exporter.ex
lib/plenario_etl/worker.ex

- Fix error in encoding maps when exporting
- Set genserver call timeouts for Exporter and Worker to `:infinity`

Export encodings

---

lib/plenario/changesets/meta_changesets.ex
test/plenario/meta_actions_test.exs
test/plenario_etl/worker_test.exs

Before we only accepted 200 responses, but that was kind of an
oversight. We should also be accepting 204s.
Fixes #216

Accept 204 When Sniffing Meta URLs

---

lib/plenario_web/controllers/web/page_controller.ex

- Prevents explorer from providing an invalid date range
- Bump to version 0.2.15
- Close #233

Block providing invalid date range for explorer

---

lib/plenario_web.ex
lib/plenario_web/controllers/api/aot_controller.ex
lib/plenario_web/controllers/api/detail_controller.ex
lib/plenario_web/controllers/api/list_controller.ex
lib/plenario_web/router.ex
lib/plenario_web/views/api/aot_view.ex
lib/plenario_web/views/api/detail_view.ex
lib/plenario_web/views/api/list_view.ex
mix.exs
test/plenario_web/controllers/api/aot_controller_test.exs
test/plenario_web/controllers/api/detail_controller_test.exs
test/plenario_web/controllers/api/list_controller_test.exs

- Close #274
- Adds routes for new API
- Instead of OPTIONS and HEAD, routes are set up with special `@` endpoints
- Need to update the wiki to reflect this
- Tested em

V2 endpoints

---

lib/plenario_web/controllers/api/detail_controller.ex
lib/plenario_web/router.ex
lib/plenario_web/views/api/detail_view.ex
mix.exs
test/plenario_web/controllers/api/detail_controller_test.exs

- Bump to version `0.6.2`
- Return raw data for `/data-sets/:slug` endpoints
- I haven't done anything special for `@describe` because I'm not sure what that means in the context for raw data
- I also haven't written tests for these responses (forgive me), I'm going to make an issue and open a testing branch after the aot endpoints are filled out
- Close #276 
```
{
"meta": {
"params": {
"page_size": 500
},
"links": {
"previous": "",
"next": "",
"current": ""
},
"counts": {
"total_records": 0,
"pages": 0,
"errors": 0,
"data": 0
}
},
"data": [
{
"__meta__": {
"state": "loaded",
"source": [
null,
"ds_9y-E2jFcCZPRG68W"
],
"context": null
},
"Street 1": "11207 S. Ewing",
"State": "IL",
"Postal Code": 60617,
"Phone": "(773) 721-1999",
"Longitude": -87.5351333203,
"Latitude": 41.6915835405, …
```

Slug endpoint

---

lib/plenario_web/controllers/api/parse_column_params.ex
lib/plenario_web/controllers/api/parse_db_operation_params.ex
lib/plenario_web/controllers/api/utils.ex
mix.exs

- Remove an unnecessary function
- Ecto casts values provided for queries on its own
- Bump to version 0.7.3

Remove `to_naive_datetime/1`

---

lib/plenario_aot/aot_data.ex
lib/plenario_aot/aot_meta.ex
lib/plenario_web/controllers/api/aot_controller.ex
lib/plenario_web/controllers/api/utils.ex
lib/plenario_web/views/api/aot_view.ex
mix.exs
test/plenario_web/controllers/api/aot_controller_test.exs

i redid the whole aot api to match with the new aot data schema.
**what works:**
- pagination
- filter by `network_name`
- filter by `node_id`
- filter by `timestamp`
- filter by `bbox`
- filter by `sensor`
and any combination of those filters. they all work with single values
and as lists.
i also updated the link generating functions so that they work with the aot api routes.
**what needs to be done:**
- filtering by observations, i.e. `?temperatre=gt:20`
this is a pretty complicated workflow and it'll be a pretty big pr when
it comes.
[describe.txt](https://github.com/UrbanCCD-UChicago/plenario2/files/1984614/describe.txt)
[get-1.txt](https://github.com/UrbanCCD-UChicago/plenario2/files/1984615/get-1.txt)
[get-2.txt](https://github.com/UrbanCCD-UChicago/plenario2/files/1984616/get-2.txt) …

AoT API - Part 1

---

priv/repo/seeds.exs

- section for a regular data set
- section for aot chicago
Run this as `mix run priv/repo/seeds.exs` to bootstrap an admin user,
data set and an aot data set.

Added Seed Script

---

lib/plenario_web/templates/shared/map.html.eex
mix.exs

The leaflet markers are broken. This fixes that, without fixing the underlying Webpack problem that caused the issue (working on it).

Leaflet marker hotfix

---

lib/plenario_web/controllers/web/page_controller.ex
mix.exs
test/plenario_web/controllers/web/page_controller_test.exs

>Remember, comparisons in Elixir using ==, >, < and friends are structural and based on the DateTime struct fields. For proper comparison between datetimes, use the compare/2 function.
Herpaderp.
- Close #310 
- Bump to version `0.9.3`

Use `DateTime.compare/2` instead of `>` operator

---

lib/plenario_web/controllers/api/list_controller.ex
lib/plenario_web/controllers/api/utils.ex
lib/plenario_web/router.ex
mix.exs
test/plenario_web/controllers/api/list_controller_test.exs

Because `bbox` was an actual column of `Meta` objects, I thought the query builder would handle things if I wrote something like `data-sets/bbox=in:{geom}`. Couldn't get things to query successfully, so I threw in some code to take `data-sets/bbox={geom}` and turn it into an `ST_Intersects` query.
- Added tests
- Bump to version `0.9.4`

Bbox keyword for metas

---

priv/repo/seeds.exs

(Weirdly, it definitely worked at least once and it shouldn't have)

Make seed script work as expected

---

lib/plenario/field_guesser.ex
lib/plenario/schemas/meta.ex
lib/plenario_etl/worker.ex
test/plenario/actions/meta_actions_test.exs
test/plenario/field_guesser_test.exs
test/plenario_etl/worker_test.exs

i was able to rip out a significant chunk of the ETL pipeline and just
use the native postgres loading stuff i added into datasetactions.
i also removed `json` as an acceptible source type for metas. there's a
couple reasons for this:
1. it cleans up the etl process
2. we don't have an immediate use case for it here
3. at some point we may need to support it, but that would most likely
be from a data set that progressively releases data rather than the
stuff we have now (basically an _all things for all time_ payload)
and at which point we would need a totally different type of etl
next up: fixing scheduling bugs and cleaning up a lot of the
create/update/admin workflow around metas

Revamped ETL System

---

lib/plenario_web/controllers/api/aot_controller.ex
lib/plenario_web/controllers/api/detail_controller.ex
lib/plenario_web/controllers/api/list_controller.ex
lib/plenario_web/controllers/api/plugs.ex
lib/plenario_web/controllers/api/utils.ex
mix.exs
test/plenario_web/controllers/api/aot_controller_test.exs
test/plenario_web/controllers/api/detail_controller_test.exs
test/plenario_web/controllers/api/list_controller_test.exs

- Limit `page_size` param, throw a 422 for invalid arguments
- Drop api controller tests (especially the AOT controller) time by a lot
before (total time 57s)
```
PlenarioWeb.Api.UtilsTest
* test generates a geospatial query using a bounding box (891.0ms)
* test generates a ranged query using bounding values (531.0ms)
* test map_to_query/2 (484.0ms)
PlenarioWeb.Api.AotControllerTest
* test GET /api/v2/aot (3297.0ms)
* test GET with filter bbox (3235.0ms)
* test GET with filter sensor (3234.0ms)
PlenarioWeb.Api.DetailControllerTest
* test GET /api/v2/data-sets/:slug populates pagination links (1000.0ms)
* test GET /api/v2/data-sets/:slug bbox query no results (1016.0ms)
* test GET /api/v2/data-sets/:slug location query (1015.0ms)
PlenarioWeb.Api.ListControllerTest
* test OPTIONS …
```

Pagination limit

---

lib/plenario_web/controllers/api/plugs.ex
mix.exs
mix.lock
test/plenario_web/controllers/api/aot_controller_test.exs
test/plenario_web/controllers/api/detail_controller_test.exs
test/plenario_web/controllers/api/list_controller_test.exs

Set up json error responses (for page size only)
```
// 20180530123551
// http://localhost:4000/api/v2/data-sets?page_size=5001
{
"errors": [
{
"title": "Unprocessable Entity",
"status": 422,
"detail": "Provided page_size '5001' must be between 0 and 5000"
}
]
}
```

Json error responses

---

.dockerignore
mix.exs

I mean, why didn't we have one before? I noticed my builds were taking
forever and the context being sent was **gianormous**.
This ignores pretty much everything except the bare bones of what's
needed to build the executable.

Added a Dockerignore File

---

lib/plenario/actions/data_set_actions.ex
lib/plenario_etl/ingest_queue.ex
lib/plenario_etl/ingest_worker.ex
mix.exs
priv/db-actions/etl/copy.sql.eex

We were having an issue consuming a few data sets. After some
investigation, I discovered that it was due to quotes being used in
header rows:
```
One,Two,"Three, or three",Four
```
This would then be translated into the Copy SQL as:
```
COPY ... ("One", "Two", ""Three, or three"", "Four") ...
```
which obviously isn't going to work.
The solution is to _regex_ split the header line rather than the naive
_string_ split. But you may ask, "Why do splits at all? Can't we just
use the CSV module and pull the keys from the first map row?". The
unfortunate answer to this is that the CSV module does not preserve
order -- if you have a header row `a,c,b` then you will get a map with
keys ordered as `a,b,c`. To preserve the order of the headers, you need
to split the line.
Fixes #344

Ingest Bug Fix

---

lib/plenario_web/controllers/api/shim_controller.ex
lib/plenario_web/views/api/detail_view.ex
lib/plenario_web/views/api/shim_view.ex
mix.exs
test/plenario_web/controllers/api/detail_controller_test.exs
test/plenario_web/controllers/api/list_controller_test.exs
test/plenario_web/controllers/api/shim_controller_test.exs

- Formats V2 responses to show up like V1 responses
- There's a little bit of janky trickery to make this work, specifically for providing "special" V1 columns
- Have to grab first location and datetime columns since there is no notion of `observed_date` column or `location` column in V2
- For all responses, data is always returned as a list. There was a special case where if the length of the data was 1, it just returned an object. But we had a discussion a while back as to why that was a bad idea, so I've fixed it in this PR

Shim endpoint response formatting

---

assets/package.json
mix.exs

Our existing semver for this package is generally sufficient, since the fix was pushed in node-sass 4.9.1 and we depend on ^4.9.0, but this ensures NPM won't pull the vulnerable 4.9.0 anyway when deduping
This will be a patch version bump, since the only direct change in node-sass is to bump their own dependency that was locking in the vulnerable package. I'm guessing it will be 0.12.1, but I'll resolve that when it comes time to merge this.
Closes #307.

Bump min node-sass version to avoid vulnerability

---

lib/plenario/actions/data_set_actions.ex
mix.exs
priv/db-actions/up/create-index.sql.eex
priv/db-actions/up/create-trgm-index.sql.eex
priv/db-actions/up/create-view.sql.eex
test/plenario/actions/data_set_actions_test.exs

We ran into an issue where data sets with long names and with
long, similarly named fields would result in naming collisions when
creating indexes. When a name exceeds a certain length, postgres
truncates it. When this happens, we wind up with naming collisions and
bring up the table/view/indexes for the data set fails.
Fixes #362

362 index names

---

lib/plenario_web/templates/web/data_set/show.html.eex
mix.exs
test/plenario_web/controllers/web/data_set_controller_test.exs

The _Request Changes_ button was being shown to all users regardless of
ownership when the data set was shown. If a non-owning user clicked the
button, it would 403.
While this is more or less the correct response, users shouldn't even be
aware of this option if they don't own the data set -- this is doubly
true for anonymous users.
This adds a simple condition to the template that ensures the user
attached to the request owns the data set -- there's a `@user_is_owner?`
variable assigned in the response anyway.
Fixes #378

Do Not Show "Request Changes" to Non-Owner Users in Data Set Show

---

README.md

Since #381 included upgraded/renamed image assets, it broke the readme header. I even had a sticky note on my monitor to not forget this 😫.

Fix now-broken README logo image

---

lib/plenario/actions/data_set_actions.ex
priv/db-actions/up/create-index.sql.eex
priv/db-actions/up/create-trgm-index.sql.eex
priv/repo/seeds.exs

The way I reset the index names didn't guarantee unique names. I went
with the assumption that we wouldn't collide IDs in the names. Well,
running the seed script blew that to hell.
The index names are now `idx_{view name}_{field type abbrv}_{field id}`.
This should be unique now.
I also fixed up the seed script.
Fixes #390

Fix Index Names

---

lib/plenario_web/controllers/api/aot_controller.ex
lib/plenario_web/controllers/api/detail_controller.ex
lib/plenario_web/controllers/api/method_not_allowed_controller.ex
lib/plenario_web/controllers/api/plugs.ex
lib/plenario_web/controllers/api/utils.ex
mix.exs

Just... wow. What an unbelievable pile of turds.
Rather than relying on a library that was clearly developed by a high
schooler, we're going to be smart about this and **just use the
functions and modules Plug already gives us**.
Plug gives us the ability to:
- set the resonse content type we want
- set the status code and message
- get an appropriate status code by either its integer value or atom
- get an appropriate message for that code
- halt further processing
We have no reason to ever consider what the client accepts via our API
because its documented to be strictly `application/json`. Clients should
only expect that content type. And overriding the `accept` content type
the client sends is a massive violation of the client/server contract.
Beyond that, as the title of the issue …

Removed God Awful Explode Library

---

lib/plenario_web/controllers/web/page_controller.ex
lib/postgres_extensions.ex
mix.exs

The functions in TsRange are relatively robust and should be able to
handle casts from erl dates to NaiveDateTimes. Unfortunately, there were
some edge cases in the database returns that didn't include
microseconds, and in a few other situtations we had abysmally formatted
dates in data files from sources.
This covers both edges. I added two new pattern matches to the casting and
wrapped the parsing in case statements defaulting to nil.
I also suppressed a compiler warning (it was irritating me).
Fixes #395

Fixed Erlang/NaiveDateTime Casting Error

---

lib/plenario_web/controllers/api/detail_controller.ex
lib/plenario_web/controllers/api/plugs.ex
lib/plenario_web/controllers/api/utils.ex
lib/plenario_web/views/api/view_utils.ex

I added docs and specs to the public functions and updated the private
`is_clean` function to be built at compile time using lists of keys and
values to define dirty types. The beauty of this is that we can just
keep updating those lists as needed without having to touch the
functions.
Let's start with the rename -- `validate_data_set` was a really awful
choice for what the function took as a parameter and what it returned.
The new name, `validate_slug_get_meta` tells you _exactly_ what it does.
I also added docs for all public functions.
Closes #421

421 Document API Helper Funcs

---

lib/plenario_web/controllers/api/utils.ex
test/plenario_web/controllers/api/list_controller_test.exs

The `meta.counts` object had inaccurate informaiton in it. This ensures
that the data count is 1 (because it is), and the total pages is 1
(because there is only one page of results in a head call), and the
total entries is what is actually in the database.
Fixes #428

Fix @head Directive Counts

---

priv/repo/migrations/000025_add_indexes.exs

These fields are **heavily** used in creating filters and they should be
properly indexed.
Closes #436
Closes #437

Added Indexes

---

lib/plenario/actions/data_set_actions.ex
lib/plenario/actions/meta_actions.ex
lib/plenario/changesets/meta_changesets.ex
test/plenario/actions/data_set_actions_test.exs

There were a bunch of errors when bringing up some of the Chicago data sets. This will take care of most of them.
We are still going to not be able to ingest Divvy, Crime and Taxi data until we get a Socrata direct strategy.
The original signature didn't account for the function being called when
the data set was still empty. This corrects that. 
TIL Postgres has a maximum table name length of 63 characters. I set an
upper bound of 58 on the name length of the MetaChangeset. Why 58 and
not 63? Because when we create the materialized view for the data set we
tack on "_view" to the table name.
Updates #235

Updates to help Alieviate Data Set Errors

---

lib/plenario_web/controllers/api/aot_controller.ex
lib/plenario_web/controllers/api/detail_controller.ex
lib/plenario_web/controllers/api/list_controller.ex
lib/plenario_web/controllers/api/plugs.ex
mix.exs
test/plenario_web/controllers/api/plugs_test.exs

- `page_size=wrong` will 400 because it's syntactically incorrect
- `page_size=0,-1` will 422 because it's semantically incorrect
- `page_size=999999999` will 403 because we refuse to serve that large a page size
- `page=wrong` will 400 because it's syntactically incorrect
- `page=0,-1` will 422 because it's semantically incorrect
- `page=99999999` will 200 and server the last useful page of data
Fixes #420

Updated API Status Codes and Terminal Pagination

---

lib/plenario_web/templates/web/page/explorer.html.eex

Since we don't really have all that great of an export strategy anymore
(we've made a lot of changes to our IO workers without giving any love
to the export process), it just makes sense at the moment to open a
blank tab and send the user to the source document.
I've updated the name of the link to _Download a Copy_ rather than
exporting to make it not seem like the users are going to just get a
view of the data set that matches their query -- the ideal export
functionality.
This still needs to fixed soon, but as we are rapidly approaching
release I don't want to screw around with big stuff like this.
Updates #371

Updated Data Set Export
